### ISSUE TITLE
How to understand code

### ISSUE THREAD

**Issue by BruceAKABear** [atomic14/ICS-43434-breakout-board#7]
I'm a little confused about the codes,Why divide by 4 in the following code. Shouldn't it be  bytes_read ?

``` c++
void I2SSampler::processI2SData(uint8_t *i2sData, size_t bytes_read)
{
    int32_t *samples = (int32_t *)i2sData;
    for (int i = 0; i < bytes_read / 4; i++)
    {
        // you may need to vary the >> 11 to fit your volume - ideally we'd have some kind of AGC here
        addSample(samples[i] >> 11);
    }
}

```

**Comment by cgreening** [comment]
Hey Bruce,

Each sample is 32 bits - so 4 bytes - so we need to divide the number of
bytes_read by 4 to get the number of sample.

Hope that makes sense.
Chris
